### ISSUE TITLE
FR: Allow passing decode options to avlizer_confluent:make_decoder & avlizer_confluent:decode

### ISSUE THREAD

**Issue by 4tyTwo** [klarna/avlizer#16]
Hi!

The underlying erlavro library allows specifying `codec_options` for the decoder however avlizer has no way to pass those options to the decoder and defaults to `[{encoding, avro_binary}]`. I would like to propose extending `avlizer_confluent:make_decoder/n` and `avlizer_confluent:decode/n` API and allowing passing those options as that would allow for a more versatile usage of the library.

According to my initial observations that should not be a difficult thing to implement and given approval, I would volunteer for creating a PR

**Comment by mikpe** [comment]
No objection to this proposal. Just make sure the code remains compatible with existing users.

**Comment by 4tyTwo** [comment]
Done in #17
